# Generated by Django 6.1.1 on 2026-09-23 15:47

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Brand",
            new_name="HairStyle",
        ),
        migrations.RemoveConstraint(
            model_name="hairstyle",
            name="unique_brand_name_ci",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="idx_product_brand",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="brand",
            new_name="hairstyle",
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_active", "hairstyle", "-created_at"],
                name="idx_product_hairstyle",
            ),
        ),
        migrations.AddConstraint(
            model_name="hairstyle",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="unique_hairstyle_name_ci",
            ),
        ),
    ]
