# Generated by Django 6.1.1 on 2026-09-25 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_productcolor_productsize"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcolor",
            name="image",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional photo associated with this color variant.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="color_variants",
                to="catalog.productimage",
            ),
        ),
        migrations.AddField(
            model_name="productcolor",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="Direct URL to color variant image.",
                max_length=500,
            ),
        ),
    ]
