# Generated by Django 6.1.1 on 2026-09-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_productreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="views_count",
            field=models.PositiveIntegerField(
                db_index=True, default=0, help_text="Total product page views."
            ),
        ),
    ]
