# Generated by Django 6.1.1 on 2026-10-06 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Blog Category",
                "verbose_name_plural": "Blog Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "excerpt",
                    models.TextField(
                        blank=True,
                        help_text="Catchy summary shown on cards, social previews, and Google snippets.",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Full post content. Supports Markdown or rich formatting."
                    ),
                ),
                (
                    "cover_image",
                    models.URLField(
                        blank=True,
                        help_text="Direct image URL or Cloudinary URL for the banner.",
                        max_length=500,
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated keywords/tags (e.g. 'wig care, lace maintenance, nairobi salon').",
                        max_length=255,
                    ),
                ),
                (
                    "author_name",
                    models.CharField(
                        default="Dallian Luxe Studio",
                        help_text="Display name for author if not linked to a specific user account.",
                        max_length=150,
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Tick to publish live to the storefront.",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Tick to highlight as hero / top headline on the Latest News page.",
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "read_time_minutes",
                    models.PositiveIntegerField(
                        default=3, help_text="Estimated minutes to read the article."
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        default=0, editable=False, help_text="Total page views count."
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="Custom Google page title. Defaults to post title if left empty.",
                        max_length=255,
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="SEO description snippet (recommended 140-160 characters).",
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated SEO target keywords for search crawlers.",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blog_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="blog.blogcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Post",
                "verbose_name_plural": "Blog Posts",
                "ordering": ["-is_featured", "-published_at", "-created_at"],
            },
        ),
    ]
